version: '3'

tasks:

  prepare-dataset-jsonl:
    desc: Prepare the dataset jsonl huggingface before insert
    cmds:
    - python prepare_dataset_hf.py

  start-milvus:
    desc: Run the milvus stack
    dir: docker/milvus
    cmds:
    - docker compose up -d

  start-openlit:
    desc: Run the openlit stack
    dir: docker/openlit
    cmds:
    - docker compose up -d

  start-qdrant:
    desc: Run the qdrant stack
    dir: docker/qdrant
    cmds:
    - docker compose up -d

  start-chroma:
    desc: Run the chroma stack
    dir: docker/chroma
    cmds:
    - docker compose up -d

  show-head-jsonl:
    desc: Show the head of the jsonl file processed
    cmds:
    - head -n 1 data/processed_dataset.jsonl | jq

  shell:
    desc: load python shell
    cmds:
    - pipenv shell

  bootstap:
    desc: Bootstrap the environment
    cmds:
    - pipenv install
    - pipenv shell && uv pip install -r requirements.txt

  # extract-gz-data:
  #   desc: extract the data videogame jsonl
  #   cmds:
  #   - gzcat data/output_dataset.jsonl.gz > data/output_dataset.jsonl

  init-db-milvus:
    desc: Initialize the database
    cmds:
    - python prepare_db.py setup --backend milvus --data-file data/processed_dataset.jsonl

  init-db-chrioma:
    desc: Initialize the database chroma
    cmds:
    - python prepare_db.py setup --backend chroma --data-file data/processed_dataset.jsonl

  init-db-qdrant:
    desc: Initialize the database qdrant
    cmds:
    - python prepare_db.py setup --backend qdrant --data-file data/processed_dataset.jsonl

  default:
    desc: List available tasks
    cmds:
    - task --list
