version: '3'

tasks:

  shell:
    desc: load python shell
    cmds:
    - pipenv shell

  bootstrap:
    desc: Bootstrap the environment
    cmds:
    - pipenv install
    - pipenv shell && uv pip install -r requirements.txt

  start-milvus:
    desc: Run the milvus stack
    dir: docker/milvus
    cmds:
    - docker compose up -d

  start-openlit:
    desc: Run the openlit stack
    dir: docker/openlit
    cmds:
    - docker compose up -d

  start-qdrant:
    desc: Run the qdrant stack
    dir: docker/qdrant
    cmds:
    - docker compose up -d

  start-chroma:
    desc: Run the chroma stack
    dir: docker/chroma
    cmds:
    - docker compose up -d

  prepare-dataset-jsonl:
    desc: Prepare the dataset jsonl huggingface before insert
    cmds:
    - python 1-prepare_dataset.py

  generate-testset:
    desc: Generate the testset query
    cmds:
    - python 3-generate-testset.py

  init-db-milvus:
    desc: Initialize the database
    cmds:
    - python 2-prepare_db.py setup --backend milvus --data-file data/processed_dataset.jsonl

  init-db-chromadb:
    desc: Initialize the database chroma
    cmds:
    - python 2-prepare_db.py setup --backend chroma --data-file data/processed_dataset.jsonl

  init-db-qdrant:
    desc: Initialize the database qdrant
    cmds:
    - python 2-prepare_db.py setup --backend qdrant --data-file data/processed_dataset.jsonl

  get-qdrant-dashboard:
    desc: Get the qdrant dashboard
    cmds:
    - open http://localhost:6333/dashboard#/collections

  get-milvus-dashboard:
    desc: Get the milvus dashboard
    cmds:
    - open http://localhost:3002/#/

  show-head-jsonl:
    desc: Show the head of the jsonl file processed
    cmds:
    - head -n 1 data/processed_dataset.jsonl | jq

default:
  desc: List available tasks
  cmds:
  - task --list
