version: '3'

tasks:
  download-hf-ds:
    desc: Download the dataset from huggingface
    cmds:
    - "huggingface-cli download  --repo-type dataset  --resume-download  --max-workers 8  --local-dir ./data/trivia  mandarjoshi/trivia_qa"

  prepare-data:
    desc: Prepare the dataset before insert
    cmds:
    - python prepare_dataset_hf.py

  build:
    desc: Build Docker image
    cmds:
    - docker compose build --push

  start-milvus:
    desc: Run the milvus stack
    dir: milvus
    cmds:
    - docker compose up -d

  stop-milvus:
    desc: Stop the milvus stack
    dir: milvus
    cmds:
    - docker compose down

  start-openlit:
    desc: Run the openlit stack
    dir: openlit
    cmds:
    - docker compose up -d

  start-qdrant:
    desc: Run the qdrant stack
    dir: qdrant
    cmds:
    - docker compose up -d

  shell:
    desc: load python shell
    cmds:
    - pipenv shell

  bootstap:
    desc: Bootstrap the environment
    cmds:
    - pipenv install
    - pipenv shell && uv pip install -r requirements.txt

  stop-qdrant:
    desc: Stop the qdrant stack
    dir: qdrant
    cmds:
    - docker compose down

  extract-gz-data:
    desc: extract the data
    cmds:
    - gzcat data/output_dataset.jsonl.gz > data/output_dataset.jsonl

  init-db-milvus:
    desc: Initialize the database
    cmds:
    - python prepare_db_milvus.py init

  init-db-qdrant:
    desc: Initialize the database qdrant
    cmds:
    - python prepare_db_qdrant.py init

  default:
    desc: List available tasks
    cmds:
    - task --list
