services:  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant:/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__LOG_LEVEL=DEBUG
volumes:
  qdrant: